# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# NOTE: No dependency group `test` is created
# since the core goal of this Gemfile is a test suite.
gem 'rake'
gem 'rspec-golden-files', '~> 0.1.3'
gem 'serverspec'

group :development do
  gem 'rubocop'
end
